/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},r=aa(this),u=function(a,b){if(b)a:{var c=r;a=a.split(".");for(var g=0;g<a.length-1;g++){var e=a[g];if(!(e in c))break a;c=c[e]}a=a[a.length-1];g=c[a];b=b(g);b!=g&&null!=b&&q(c,a,{configurable:!0,writable:!0,value:b})}};
u("Symbol",function(a){if(a)return a;var b=function(l,d){this.g=l;q(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",g=0,e=function(l){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(l||"")+"_"+g++,l)};return e});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var g=r[b[c]];"function"===typeof g&&"function"!=typeof g.prototype[a]&&q(g.prototype,a,{configurable:!0,writable:!0,value:function(){return ba(n(this))}})}return a});
var ba=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},v=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:n(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},ca="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},w;
if("function"==typeof Object.setPrototypeOf)w=Object.setPrototypeOf;else{var x;a:{var da={a:!0},y={};try{y.__proto__=da;x=y.a;break a}catch(a){}x=!1}w=x?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var z=w,A=function(a,b){a.prototype=ca(b.prototype);a.prototype.constructor=a;if(z)z(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,c);g&&Object.defineProperty(a,c,g)}else a[c]=b[c];a.ma=b.prototype};
u("Promise",function(a){function b(){this.g=null}function c(d){return d instanceof e?d:new e(function(f){f(d)})}if(a)return a;b.prototype.i=function(d){if(null==this.g){this.g=[];var f=this;this.j(function(){f.o()})}this.g.push(d)};var g=r.setTimeout;b.prototype.j=function(d){g(d,0)};b.prototype.o=function(){for(;this.g&&this.g.length;){var d=this.g;this.g=[];for(var f=0;f<d.length;++f){var h=d[f];d[f]=null;try{h()}catch(k){this.l(k)}}}this.g=null};b.prototype.l=function(d){this.j(function(){throw d;
})};var e=function(d){this.i=0;this.j=void 0;this.g=[];this.H=!1;var f=this.l();try{d(f.resolve,f.reject)}catch(h){f.reject(h)}};e.prototype.l=function(){function d(k){return function(m){h||(h=!0,k.call(f,m))}}var f=this,h=!1;return{resolve:d(this.V),reject:d(this.o)}};e.prototype.V=function(d){if(d===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof e)this.ha(d);else{a:switch(typeof d){case "object":var f=null!=d;break a;case "function":f=!0;break a;default:f=
!1}f?this.U(d):this.v(d)}};e.prototype.U=function(d){var f=void 0;try{f=d.then}catch(h){this.o(h);return}"function"==typeof f?this.ka(f,d):this.v(d)};e.prototype.o=function(d){this.N(2,d)};e.prototype.v=function(d){this.N(1,d)};e.prototype.N=function(d,f){if(0!=this.i)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.i);this.i=d;this.j=f;2===this.i&&this.W();this.O()};e.prototype.W=function(){var d=this;g(function(){if(d.T()){var f=r.console;"undefined"!==typeof f&&
f.error(d.j)}},1)};e.prototype.T=function(){if(this.H)return!1;var d=r.CustomEvent,f=r.Event,h=r.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):"function"===typeof f?d=new f("unhandledrejection",{cancelable:!0}):(d=r.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.j;return h(d)};e.prototype.O=function(){if(null!=this.g){for(var d=0;d<this.g.length;++d)l.i(this.g[d]);
this.g=null}};var l=new b;e.prototype.ha=function(d){var f=this.l();d.s(f.resolve,f.reject)};e.prototype.ka=function(d,f){var h=this.l();try{d.call(f,h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.then=function(d,f){function h(p,t){return"function"==typeof p?function(G){try{k(p(G))}catch(H){m(H)}}:t}var k,m,I=new e(function(p,t){k=p;m=t});this.s(h(d,k),h(f,m));return I};e.prototype.catch=function(d){return this.then(void 0,d)};e.prototype.s=function(d,f){function h(){switch(k.i){case 1:d(k.j);
break;case 2:f(k.j);break;default:throw Error("Unexpected state: "+k.i);}}var k=this;null==this.g?l.i(h):this.g.push(h);this.H=!0};e.resolve=c;e.reject=function(d){return new e(function(f,h){h(d)})};e.race=function(d){return new e(function(f,h){for(var k=v(d),m=k.next();!m.done;m=k.next())c(m.value).s(f,h)})};e.all=function(d){var f=v(d),h=f.next();return h.done?c([]):new e(function(k,m){function I(G){return function(H){p[G]=H;t--;0==t&&k(p)}}var p=[],t=0;do p.push(void 0),t++,c(h.value).s(I(p.length-
1),m),h=f.next();while(!h.done)})};return e});var ea=function(a,b){a instanceof String&&(a+="");var c=0,g=!1,e={next:function(){if(!g&&c<a.length){var l=c++;return{value:b(l,a[l]),done:!1}}g=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};u("Array.prototype.entries",function(a){return a?a:function(){return ea(this,function(b,c){return[b,c]})}});
var B=this||self,C=function(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.na=function(g,e,l){for(var d=Array(arguments.length-2),f=2;f<arguments.length;f++)d[f-2]=arguments[f];return b.prototype[e].apply(g,d)}},D=function(a){return a};var E=function(a){this.g=a};function F(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,F);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}C(F,Error);F.prototype.name="CustomError";function J(a,b){a=a.split("%s");for(var c="",g=a.length-1,e=0;e<g;e++)c+=a[e]+(e<b.length?b[e]:"%s");F.call(this,c+a[g])}C(J,F);J.prototype.name="AssertionError";var K=function(a,b,c){if(!a){var g="Assertion failed";if(b){g+=": "+b;var e=Array.prototype.slice.call(arguments,2)}throw new J(""+g,e||[]);}},L=function(a,b){throw new J("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var M=function(a,b){this.g=a;this.i=b||null};A(M,E);M.prototype.then=function(a,b,c){var g;a&&(g=fa(this,a));this.g.aa(g,b,c)};var fa=function(a,b){var c=a.i;return c?function(g){b.call(this,new c(g))}:b};var ha=[];var N=function(a){this.g=a||gbar.a;this.i=null};A(N,E);var ia=function(){K(!Object.isSealed(N),"Cannot use getInstance() with a sealed constructor.");var a="u";if(N.u&&N.hasOwnProperty(a))a=N.u;else{ha.push(N);var b=new N;N.u=b;K(N.hasOwnProperty(a),"Could not instantiate singleton.");a=b}a.i||(a.i=new M(a.g.bh()));return a.i};var O;var Q=function(a,b){this.g=a===P&&b||"";this.i=ja};Q.prototype.toString=function(){return"Const{"+this.g+"}"};var ka=function(a){if(a instanceof Q&&a.constructor===Q&&a.i===ja)return a.g;L("expected object of type Const, got '"+a+"'");return"type_error:Const"},ja={},P={};var R=function(a,b){this.g=b===la?a:""};R.prototype.toString=function(){return this.g+""};var la={},ma=function(a){if(void 0===O){var b=null;var c=B.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:D,createScript:D,createScriptURL:D})}catch(g){B.console&&B.console.error(g.message)}O=b}else O=b}a=(b=O)?b.createScriptURL(a):a;return new R(a,la)};var S=function(a,b){this.name=a;this.value=b};S.prototype.toString=function(){return this.name};
var na=new S("OFF",Infinity),oa=new S("WARNING",900),pa=new S("CONFIG",700),qa=function(){},ra,sa=function(){},ta=function(a,b){this.g=null;this.l=[];this.i=(void 0===b?null:b)||null;this.j=[];this.o={g:function(){return a}}},ua=function(a){if(a.g)return a.g;if(a.i)return ua(a.i);L("Root logger has no level set.");return na},va=function(a){for(var b=new sa;a;)a.l.forEach(function(c){c(b)}),a=a.i},wa=function(){this.entries={};var a=new ta("");a.g=pa;this.entries[""]=a},T,U=function(a,b){var c=a.entries[b];
if(c)return c;c=U(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var g=new ta(b,c);a.entries[b]=g;c.j.push(g);return g},V=function(){T||(T=new wa);return T};/*

 SPDX-License-Identifier: Apache-2.0
*/
var xa=[],ya=function(a){var b;if(b=U(V(),"safevalues").o){a="A URL with content '"+a+"' was sanitized away.";var c;if(c=b)if(c=b&&oa){c=oa.value;var g=b?ua(U(V(),b.g())):na;c=c>=g.value}c&&(b=U(V(),b.g()),"function"===typeof a&&a(),ra||(ra=new qa),va(b))}};-1===xa.indexOf(ya)&&xa.push(ya);function W(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");za?(Aa=!0,Ba&&X()):X()}var X,Y=null,Z=window,Ca=Z.colabExperiments&&Z.colabExperiments.gis_auth,Da=Z.colabExperiments&&Z.colabExperiments.first_party_auth,Ea=Z.colabExperiments&&Z.colabExperiments.cloud_oauth,Fa=Z.colabExperiments&&Z.colabExperiments.rt,za=Ca&&(!Da||Ea||Fa),Ba=!1,Aa=!1,Ga=document.getElementsByTagName("script")[0],Ha=ma(ka(new Q(P,"https://accounts.google.com/gsi/client")));
function Ia(){if(Y)return Y;window.performance.mark("gapi_load_start");return Y=new Promise(function(a,b){X=a;za&&Ja(function(){b(Error("Error loading "+Ha))});if(Da&&"undefined"!==typeof gbar)ia().then(function(){Ca?gapi.load("client",W):gapi.load("auth:client",W)});else{Z.gapi_onload=W;var c=ma(ka(new Q(P,"https://apis.google.com/js/client.js")));Ka({src:c,onerror:function(){b(Error("Error loading "+c))}})}})}function Ja(a){Ka({src:Ha,onload:function(){Ba=!0;Aa&&X()},onerror:a})}
function Ka(a){var b=document;var c="SCRIPT";"application/xhtml+xml"===b.contentType&&(c=c.toLowerCase());c=b.createElement(c);b=a.src;if(b instanceof R&&b.constructor===R)b=b.g;else{var g=typeof b;L("expected object of type TrustedResourceUrl, got '"+b+"' of type "+("object"!=g?g:b?Array.isArray(b)?"array":g:"null"));b="type_error:TrustedResourceUrl"}c.src=b;var e,l;(e=(b=null==(l=(e=(c.ownerDocument&&c.ownerDocument.defaultView||window).document).querySelector)?void 0:l.call(e,"script[nonce]"))?
b.nonce||b.getAttribute("nonce")||"":"")&&c.setAttribute("nonce",e);c.async=!0;a.onload&&(c.onload=a.onload);a.onerror&&(c.onerror=a.onerror);Ga.parentNode.insertBefore(c,Ga)}Z.colab_gapi_loader={load:Ia};Ia().then(function(){},function(){});
